#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="aweomse-GNOME-Flashback:GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=aweomse-gnome-flashback --disable-acceleration-check "$@"
